CREATE DATABASE boomerang;

use boomerang;

CREATE TABLE users (
	id INT(11) UNSIGNED AUTO_INCREMENT , 
	name VARCHAR(30) NOT NULL,
	email VARCHAR(50) NOT NULL, PRIMARY KEY,
	user-name VARCHAR(20) NOT NULL, PRIMARY KEY,
	password VARCHAR(50),
);